baseURL = "https://lenguyenthanh.com"
languageCode = "en-us"
title = "Thanh Le"
theme = "hermit"

# enableGitInfo = true
pygmentsCodefences  = true
pygmentsUseClasses  = true
hasCJKLanguage = false  # If there're Chinese/Japanese/Korean Languages in the content, enable this.
rssLimit = 10  # Maximum number of items in the RSS feed.
enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/
# googleAnalytics = "UA-123-45"
# disqusShortname = "yourdiscussshortname"

[author]
  name = "Thanh Le"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag = "tags"
  category = ""  # Categories are disabled by default.

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # themeColor = "#494f5c"  # Theme color in meta tags.
  homeSubtitle = "My personal website"
  footerCopyright = ""
  # gitUrl = "https://github.com/Someone/SomeRepo/commit/" # Prefix of link to the git commit detail page. GitInfo must be enabled.
  justifyContent = false  # Set "text-align: justify" to .content, requires extended version of Hugo
  # bgImg = ""  #  Homepage background-image URL

  # Social Icons
  # Check https://github.com/Track3/hermit#social-icons for more info.
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/lenguyenthanh"

  [[params.social]]
    name = "github"
    url = "https://github.com/lenguyenthanh"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/lenguyenthanh"

  [[params.social]]
    name = "gitlab"
    url = "https://gitlab.com/lenguyenthanh"

[menu]

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 20
